/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as GraphqlIndexRouteImport } from './routes/graphql/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ChatRoomIdRouteImport } from './routes/chat/$roomId'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlIndexRoute = GraphqlIndexRouteImport.update({
  id: '/graphql/',
  path: '/graphql/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoomIdRoute = ChatRoomIdRouteImport.update({
  id: '/chat/$roomId',
  path: '/chat/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/registration': typeof RegistrationRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/chat': typeof ChatIndexRoute
  '/graphql': typeof GraphqlIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/registration': typeof RegistrationRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/chat': typeof ChatIndexRoute
  '/graphql': typeof GraphqlIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/registration': typeof RegistrationRoute
  '/chat/$roomId': typeof ChatRoomIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/chat/': typeof ChatIndexRoute
  '/graphql/': typeof GraphqlIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/registration'
    | '/chat/$roomId'
    | '/products/$productId'
    | '/chat'
    | '/graphql'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/registration'
    | '/chat/$roomId'
    | '/products/$productId'
    | '/chat'
    | '/graphql'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/registration'
    | '/chat/$roomId'
    | '/products/$productId'
    | '/chat/'
    | '/graphql/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRoute
  RegistrationRoute: typeof RegistrationRoute
  ChatRoomIdRoute: typeof ChatRoomIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  GraphqlIndexRoute: typeof GraphqlIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql/': {
      id: '/graphql/'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$roomId': {
      id: '/chat/$roomId'
      path: '/chat/$roomId'
      fullPath: '/chat/$roomId'
      preLoaderRoute: typeof ChatRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRoute,
  RegistrationRoute: RegistrationRoute,
  ChatRoomIdRoute: ChatRoomIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  GraphqlIndexRoute: GraphqlIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
