/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const RegistrationLazyRouteImport = createFileRoute('/registration')()
const AuthorizeLazyRouteImport = createFileRoute('/authorize')()
const IndexLazyRouteImport = createFileRoute('/')()
const ProductsIndexLazyRouteImport = createFileRoute('/products/')()
const ProductsProductIdLazyRouteImport = createFileRoute(
  '/products/$productId',
)()

const RegistrationLazyRoute = RegistrationLazyRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/registration.lazy').then((d) => d.Route))
const AuthorizeLazyRoute = AuthorizeLazyRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/authorize.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProductsIndexLazyRoute = ProductsIndexLazyRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/products/index.lazy').then((d) => d.Route),
)
const ProductsProductIdLazyRoute = ProductsProductIdLazyRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/products/$productId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/authorize': typeof AuthorizeLazyRoute
  '/registration': typeof RegistrationLazyRoute
  '/products/$productId': typeof ProductsProductIdLazyRoute
  '/products': typeof ProductsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/authorize': typeof AuthorizeLazyRoute
  '/registration': typeof RegistrationLazyRoute
  '/products/$productId': typeof ProductsProductIdLazyRoute
  '/products': typeof ProductsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/authorize': typeof AuthorizeLazyRoute
  '/registration': typeof RegistrationLazyRoute
  '/products/$productId': typeof ProductsProductIdLazyRoute
  '/products/': typeof ProductsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/registration'
    | '/products/$productId'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/registration'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/registration'
    | '/products/$productId'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthorizeLazyRoute: typeof AuthorizeLazyRoute
  RegistrationLazyRoute: typeof RegistrationLazyRoute
  ProductsProductIdLazyRoute: typeof ProductsProductIdLazyRoute
  ProductsIndexLazyRoute: typeof ProductsIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthorizeLazyRoute: AuthorizeLazyRoute,
  RegistrationLazyRoute: RegistrationLazyRoute,
  ProductsProductIdLazyRoute: ProductsProductIdLazyRoute,
  ProductsIndexLazyRoute: ProductsIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
